[workspace]
members = ["akasabi", "lab"]
solver = "2"

[workspace.package]
authors = ["ShizukaKokoro"]
edition = "2021"

[workspace.dependencies]
thiserror = "2.0.11"
log = "0.4.25"

akasabi = { path = "akasabi" }

[workspace.dev-dependencies]
pretty_assertions = "1.4.1"
rstest = "0.24.0"
