[workspace]
members = ["akasabi", "lab"]
resolver = "2"

[workspace.package]
authors = ["ShizukaKokoro"]
edition = "2021"

[workspace.dependencies]
log = "0.4.25"
env_logger = "0.11.6"

pretty_assertions = "1.4.1"
rstest = "0.24.0"
