[package]
name = "akasabi"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
rstest.workspace = true
